const TODOS_FETCH_REQUESTED = 'TODOS_FETCH_REQUESTED';
const TODOS_FETCH_SUCCEEDED = 'TODOS_FETCH_SUCCEEDED';
const TODOS_FETCH_FAILED = 'TODOS_FETCH_FAILED';

const todosFetchRequested = () => ({
  type: TODOS_FETCH_REQUESTED
})


export {TODOS_FETCH_REQUESTED, TODOS_FETCH_SUCCEEDED, TODOS_FETCH_FAILED, todosFetchRequested};
